// lib/cta-knowledge-base/seed-data.ts — Curated CTA database with scores

import type { CTASeedEntry } from "./types"

export const CTA_SEED_DATA: readonly CTASeedEntry[] = [
  // ── High performers (80-95) ───────────────────────────────
  {
    cta: "Build & Price Your RAV4",
    score: 82,
    category: "configurator",
    segments: ["suv"],
    seasons: ["Q1", "Q2", "Q3", "Q4"],
    funnelStages: ["consideration", "intent"],
    whyItWorks: "Action-specific with model name, sets clear expectation of configurator experience",
  },
  {
    cta: "See If You Qualify for $7,500",
    score: 88,
    category: "incentive",
    segments: ["ev"],
    seasons: ["Q1", "Q2", "Q3", "Q4"],
    funnelStages: ["intent", "purchase"],
    whyItWorks: "Personal relevance, specific dollar value, EV tax credit hook",
  },
  {
    cta: "Reserve Your Cybertruck Now",
    score: 85,
    category: "urgency",
    segments: ["truck", "ev"],
    seasons: ["Q1", "Q2", "Q3", "Q4"],
    funnelStages: ["intent", "purchase"],
    whyItWorks: "Urgency + exclusivity, specific model creates desire",
  },
  {
    cta: "Compare F-150 vs Silverado",
    score: 80,
    category: "informational",
    segments: ["truck"],
    seasons: ["Q1", "Q2", "Q3", "Q4"],
    funnelStages: ["consideration"],
    whyItWorks: "Addresses natural comparison behavior, specific models show relevance",
  },
  {
    cta: "Unlock Your Employee Pricing",
    score: 86,
    category: "incentive",
    segments: ["truck", "sedan", "suv"],
    seasons: ["Q3", "Q4"],
    funnelStages: ["intent", "purchase"],
    whyItWorks: "Exclusive access framing, personal benefit, urgency of limited program",
  },
  {
    cta: "Schedule Your Test Drive Today",
    score: 78,
    category: "urgency",
    segments: ["truck", "sedan", "suv", "luxury", "ev", "sports"],
    seasons: ["Q1", "Q2", "Q3", "Q4"],
    funnelStages: ["intent"],
    whyItWorks: "Clear next step, time-bound with 'Today', physical experience hook",
  },
  {
    cta: "Calculate Your Monthly Payment",
    score: 81,
    category: "value",
    segments: ["truck", "sedan", "suv", "luxury", "ev"],
    seasons: ["Q1", "Q2", "Q3", "Q4"],
    funnelStages: ["intent", "purchase"],
    whyItWorks: "Addresses #1 buyer concern, personal financial relevance, tool-based engagement",
  },
  {
    cta: "Claim Your Year-End Bonus Cash",
    score: 84,
    category: "incentive",
    segments: ["truck", "sedan", "suv"],
    seasons: ["Q4"],
    funnelStages: ["intent", "purchase"],
    whyItWorks: "Time-limited incentive, direct value proposition, ownership language",
  },
  {
    cta: "Design Your Dream 911",
    score: 83,
    category: "configurator",
    segments: ["sports", "luxury"],
    seasons: ["Q1", "Q2", "Q3", "Q4"],
    funnelStages: ["awareness", "consideration"],
    whyItWorks: "Emotional aspiration, specific model prestige, creative engagement",
  },
  {
    cta: "Get $5,000 Off MSRP This Weekend",
    score: 90,
    category: "incentive",
    segments: ["truck", "sedan", "suv"],
    seasons: ["Q3", "Q4"],
    funnelStages: ["purchase"],
    whyItWorks: "Specific dollar amount, extreme time urgency, clear value",
  },
  {
    cta: "See What's In Stock Near You",
    score: 72,
    category: "informational",
    segments: ["truck", "sedan", "suv", "ev"],
    seasons: ["Q1", "Q2", "Q3", "Q4"],
    funnelStages: ["consideration", "intent"],
    whyItWorks: "Local relevance, availability-driven urgency, low commitment",
  },
  {
    cta: "Experience the All-New EV6",
    score: 75,
    category: "emotional",
    segments: ["ev"],
    seasons: ["Q1", "Q2", "Q3", "Q4"],
    funnelStages: ["awareness"],
    whyItWorks: "New model excitement, experiential language, category curiosity",
  },

  // ── Mid performers (50-75) ────────────────────────────────
  {
    cta: "Explore Our Lineup",
    score: 52,
    category: "informational",
    segments: ["truck", "sedan", "suv", "luxury", "ev", "sports"],
    seasons: ["Q1", "Q2", "Q3", "Q4"],
    funnelStages: ["awareness"],
    whyItWorks: "Broad but low urgency, no specific value proposition",
  },
  {
    cta: "Shop New Inventory",
    score: 58,
    category: "informational",
    segments: ["truck", "sedan", "suv"],
    seasons: ["Q1", "Q2", "Q3", "Q4"],
    funnelStages: ["consideration"],
    whyItWorks: "Action-oriented but generic, no differentiating value",
  },
  {
    cta: "View Special Offers",
    score: 55,
    category: "value",
    segments: ["truck", "sedan", "suv", "luxury"],
    seasons: ["Q1", "Q2", "Q3", "Q4"],
    funnelStages: ["consideration"],
    whyItWorks: "Promise of value but vague, no specificity about offers",
  },
  {
    cta: "Find Your Perfect Match",
    score: 60,
    category: "emotional",
    segments: ["sedan", "suv"],
    seasons: ["Q1", "Q2", "Q3", "Q4"],
    funnelStages: ["awareness", "consideration"],
    whyItWorks: "Personal framing, but lacks actionable specificity",
  },
  {
    cta: "Check Availability",
    score: 62,
    category: "informational",
    segments: ["truck", "sedan", "suv", "ev"],
    seasons: ["Q1", "Q2", "Q3", "Q4"],
    funnelStages: ["intent"],
    whyItWorks: "Implies scarcity, but generic action with no model specificity",
  },
  {
    cta: "Request a Quote",
    score: 65,
    category: "value",
    segments: ["truck", "sedan", "suv", "luxury"],
    seasons: ["Q1", "Q2", "Q3", "Q4"],
    funnelStages: ["intent"],
    whyItWorks: "Clear funnel progression, but feels transactional without warmth",
  },
  {
    cta: "See the Difference",
    score: 48,
    category: "emotional",
    segments: ["ev", "luxury"],
    seasons: ["Q1", "Q2", "Q3", "Q4"],
    funnelStages: ["awareness"],
    whyItWorks: "Curiosity gap but too vague, no clear benefit or next step",
  },
  {
    cta: "Browse Models",
    score: 45,
    category: "informational",
    segments: ["truck", "sedan", "suv", "luxury", "ev", "sports"],
    seasons: ["Q1", "Q2", "Q3", "Q4"],
    funnelStages: ["awareness"],
    whyItWorks: "Passive browsing language, no urgency or value signal",
  },
  {
    cta: "Contact Us Today",
    score: 50,
    category: "informational",
    segments: ["truck", "sedan", "suv", "luxury", "ev", "sports"],
    seasons: ["Q1", "Q2", "Q3", "Q4"],
    funnelStages: ["intent"],
    whyItWorks: "Clear action but generic, no reason given to make contact",
  },

  // ── Low performers (20-45) ────────────────────────────────
  {
    cta: "Learn More",
    score: 28,
    category: "informational",
    segments: ["truck", "sedan", "suv", "luxury", "ev", "sports"],
    seasons: ["Q1", "Q2", "Q3", "Q4"],
    funnelStages: ["awareness"],
    whyItWorks: "Most generic CTA possible, tells shopper nothing about what they'll learn",
  },
  {
    cta: "Get More Info",
    score: 25,
    category: "informational",
    segments: ["truck", "sedan", "suv", "luxury", "ev", "sports"],
    seasons: ["Q1", "Q2", "Q3", "Q4"],
    funnelStages: ["awareness"],
    whyItWorks: "Equally generic to Learn More, no value proposition or specificity",
  },
  {
    cta: "Click Here",
    score: 15,
    category: "informational",
    segments: ["truck", "sedan", "suv", "luxury", "ev", "sports"],
    seasons: ["Q1", "Q2", "Q3", "Q4"],
    funnelStages: ["awareness"],
    whyItWorks: "Zero information about destination or value, worst practice CTA",
  },
  {
    cta: "Visit Website",
    score: 20,
    category: "informational",
    segments: ["truck", "sedan", "suv", "luxury", "ev", "sports"],
    seasons: ["Q1", "Q2", "Q3", "Q4"],
    funnelStages: ["awareness"],
    whyItWorks: "States the obvious, no differentiation or value signal",
  },
  {
    cta: "Submit",
    score: 18,
    category: "informational",
    segments: ["truck", "sedan", "suv", "luxury", "ev", "sports"],
    seasons: ["Q1", "Q2", "Q3", "Q4"],
    funnelStages: ["purchase"],
    whyItWorks: "Transactional label, no benefit framing, feels like work not reward",
  },
  {
    cta: "Sign Up",
    score: 30,
    category: "informational",
    segments: ["truck", "sedan", "suv", "luxury", "ev", "sports"],
    seasons: ["Q1", "Q2", "Q3", "Q4"],
    funnelStages: ["awareness"],
    whyItWorks: "Commitment-heavy language for automotive, no value exchange explained",
  },

  // ── Segment-specific high performers ──────────────────────
  {
    cta: "Configure Your F-150 Lightning",
    score: 87,
    category: "configurator",
    segments: ["truck", "ev"],
    seasons: ["Q1", "Q2", "Q3", "Q4"],
    funnelStages: ["consideration", "intent"],
    whyItWorks: "Truck customization culture + EV novelty, specific model builds engagement",
  },
  {
    cta: "See 0% APR Offers",
    score: 79,
    category: "incentive",
    segments: ["sedan", "suv"],
    seasons: ["Q2", "Q3"],
    funnelStages: ["intent", "purchase"],
    whyItWorks: "Specific financial benefit, immediate value recognition",
  },
  {
    cta: "Book Your Private Showing",
    score: 82,
    category: "emotional",
    segments: ["luxury"],
    seasons: ["Q1", "Q2", "Q3", "Q4"],
    funnelStages: ["intent"],
    whyItWorks: "Exclusivity and personal attention, luxury buyer psychology",
  },
  {
    cta: "Trade In & Upgrade Today",
    score: 76,
    category: "value",
    segments: ["truck", "sedan", "suv"],
    seasons: ["Q3", "Q4"],
    funnelStages: ["intent", "purchase"],
    whyItWorks: "Addresses equity concern, immediate progression, time urgency",
  },
  {
    cta: "Watch the Reveal",
    score: 71,
    category: "emotional",
    segments: ["sports", "ev", "luxury"],
    seasons: ["Q1", "Q2"],
    funnelStages: ["awareness"],
    whyItWorks: "Event-based urgency, video engagement, brand storytelling hook",
  },
  {
    cta: "Estimate Your Trade-In Value",
    score: 74,
    category: "value",
    segments: ["truck", "sedan", "suv"],
    seasons: ["Q1", "Q2", "Q3", "Q4"],
    funnelStages: ["consideration", "intent"],
    whyItWorks: "Tool-based engagement, personal financial relevance, low commitment",
  },
  {
    cta: "Join the Waitlist",
    score: 70,
    category: "urgency",
    segments: ["ev", "sports"],
    seasons: ["Q1", "Q2", "Q3", "Q4"],
    funnelStages: ["intent"],
    whyItWorks: "Scarcity signal, exclusivity, works for hype-driven launches",
  },
  {
    cta: "Get Pre-Approved in 60 Seconds",
    score: 83,
    category: "value",
    segments: ["sedan", "suv", "truck"],
    seasons: ["Q1", "Q2", "Q3", "Q4"],
    funnelStages: ["intent", "purchase"],
    whyItWorks: "Speed promise, removes friction fear, specific time commitment",
  },
  {
    cta: "See How Much You'll Save",
    score: 77,
    category: "value",
    segments: ["ev", "sedan"],
    seasons: ["Q1", "Q2", "Q3", "Q4"],
    funnelStages: ["consideration"],
    whyItWorks: "Personal savings framing, curiosity gap, positive outcome focus",
  },
  {
    cta: "Customize Your Wrangler",
    score: 84,
    category: "configurator",
    segments: ["suv", "truck"],
    seasons: ["Q1", "Q2", "Q3", "Q4"],
    funnelStages: ["consideration", "intent"],
    whyItWorks: "Wrangler buyers expect customization, brand-aligned language",
  },
  {
    cta: "Explore EV Tax Credits",
    score: 73,
    category: "incentive",
    segments: ["ev"],
    seasons: ["Q1", "Q4"],
    funnelStages: ["consideration"],
    whyItWorks: "Policy-relevant value, educational hook, addresses cost barrier",
  },
  {
    cta: "Find Certified Pre-Owned Deals",
    score: 68,
    category: "value",
    segments: ["sedan", "suv", "luxury"],
    seasons: ["Q1", "Q2", "Q3", "Q4"],
    funnelStages: ["consideration"],
    whyItWorks: "Trust signal (certified), value framing (deals), specific inventory type",
  },
  {
    cta: "Start Your Order",
    score: 72,
    category: "urgency",
    segments: ["truck", "ev"],
    seasons: ["Q1", "Q2", "Q3", "Q4"],
    funnelStages: ["purchase"],
    whyItWorks: "Modern build-to-order framing, commitment but with control",
  },
  {
    cta: "Discover What Sets Us Apart",
    score: 42,
    category: "emotional",
    segments: ["luxury", "ev"],
    seasons: ["Q1", "Q2", "Q3", "Q4"],
    funnelStages: ["awareness"],
    whyItWorks: "Curiosity-based but self-focused instead of buyer-focused",
  },
  {
    cta: "Take the Virtual Tour",
    score: 66,
    category: "emotional",
    segments: ["luxury", "ev"],
    seasons: ["Q1", "Q2", "Q3", "Q4"],
    funnelStages: ["consideration"],
    whyItWorks: "Interactive experience promise, digital-first engagement, low barrier",
  },
  {
    cta: "Lock In Today's Price",
    score: 85,
    category: "urgency",
    segments: ["truck", "sedan", "suv"],
    seasons: ["Q3", "Q4"],
    funnelStages: ["purchase"],
    whyItWorks: "Price protection anxiety, immediate action trigger, assumes rising prices",
  },
  {
    cta: "See Real Owner Reviews",
    score: 69,
    category: "informational",
    segments: ["truck", "sedan", "suv", "ev"],
    seasons: ["Q1", "Q2", "Q3", "Q4"],
    funnelStages: ["consideration"],
    whyItWorks: "Social proof, authenticity signal, research-stage relevant",
  },
  {
    cta: "Get Your Instant Cash Offer",
    score: 80,
    category: "value",
    segments: ["truck", "sedan", "suv"],
    seasons: ["Q1", "Q2", "Q3", "Q4"],
    funnelStages: ["intent", "purchase"],
    whyItWorks: "Speed + money combination, addresses trade-in uncertainty, personal result",
  },
  {
    cta: "Compare Trims & Features",
    score: 64,
    category: "informational",
    segments: ["truck", "sedan", "suv", "ev"],
    seasons: ["Q1", "Q2", "Q3", "Q4"],
    funnelStages: ["consideration"],
    whyItWorks: "Decision-helping tool, research-stage aligned, but lacks emotional pull",
  },
  {
    cta: "Apply for Financing",
    score: 56,
    category: "value",
    segments: ["truck", "sedan", "suv"],
    seasons: ["Q1", "Q2", "Q3", "Q4"],
    funnelStages: ["purchase"],
    whyItWorks: "Clear intent signal, but feels like paperwork rather than benefit",
  },
  {
    cta: "View Current Specials",
    score: 54,
    category: "value",
    segments: ["truck", "sedan", "suv"],
    seasons: ["Q1", "Q2", "Q3", "Q4"],
    funnelStages: ["consideration"],
    whyItWorks: "Value promise but passive, no specificity about what specials include",
  },
  {
    cta: "Download the Brochure",
    score: 35,
    category: "informational",
    segments: ["luxury", "sports"],
    seasons: ["Q1", "Q2", "Q3", "Q4"],
    funnelStages: ["awareness"],
    whyItWorks: "Outdated format expectation, high-friction for digital audience",
  },
  {
    cta: "Watch the Performance Test",
    score: 74,
    category: "emotional",
    segments: ["sports", "truck", "ev"],
    seasons: ["Q1", "Q2", "Q3", "Q4"],
    funnelStages: ["awareness", "consideration"],
    whyItWorks: "Video proof of capability, performance-buyer hook, entertaining content",
  },
  {
    cta: "See It in Your Driveway",
    score: 76,
    category: "emotional",
    segments: ["sedan", "suv", "truck"],
    seasons: ["Q1", "Q2", "Q3", "Q4"],
    funnelStages: ["consideration", "intent"],
    whyItWorks: "AR/visualization hook, ownership imagination, personal context",
  },
  {
    cta: "Lease from $299/mo",
    score: 82,
    category: "incentive",
    segments: ["sedan", "suv"],
    seasons: ["Q2", "Q3", "Q4"],
    funnelStages: ["intent", "purchase"],
    whyItWorks: "Specific monthly cost, low-barrier entry, immediate affordability signal",
  },
  {
    cta: "Find Yours",
    score: 58,
    category: "emotional",
    segments: ["truck", "sedan", "suv", "ev"],
    seasons: ["Q1", "Q2", "Q3", "Q4"],
    funnelStages: ["consideration"],
    whyItWorks: "Ownership language, personal but lacks specificity about what they'll find",
  },
] as const
